# Generated by Django 3.0.7 on 2020-06-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personelName', models.CharField(max_length=50)),
                ('titlePersonel', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('personelImage', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cv.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=70)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=50)),
                ('LastName', models.CharField(blank=True, max_length=50)),
                ('DateOfBirth', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=13)),
                ('Tel', models.TextField(blank=True, max_length=16)),
                ('Summary', models.CharField(blank=True, max_length=200)),
                ('cvImage', models.ImageField(blank=True, upload_to='images/')),
                ('EducationalLevel', models.CharField(blank=True, max_length=10)),
                ('Adress', models.CharField(blank=True, max_length=100)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Personnel')),
            ],
        ),
    ]
