# Generated by Django 3.0.7 on 2020-07-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=5)),
                ('WorkExperienceName', models.CharField(blank=True, max_length=70)),
                ('Title', models.CharField(blank=True, max_length=70)),
                ('FromYear', models.CharField(blank=True, max_length=70)),
                ('ToYear', models.CharField(blank=True, max_length=70)),
                ('Description', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='image',
            new_name='cvImage',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='update_time',
        ),
        migrations.AddField(
            model_name='cv',
            name='Adress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='EducationalLevel',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cv',
            name='FirstName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cv',
            name='ID',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='LastName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cv',
            name='Summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cv',
            name='Tel',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=13),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personelName', models.CharField(max_length=50)),
                ('titlePersonel', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('personelImage', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cv.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=70)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Personnel')),
            ],
        ),
    ]
