# Generated by Django 3.0.7 on 2020-06-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='deneme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
