# Generated by Django 3.0.7 on 2020-06-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_deneme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='deneme',
        ),
    ]
