# Generated by Django 3.0.7 on 2020-07-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200701_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=5)),
                ('CertificationName', models.CharField(blank=True, max_length=70, null=True)),
                ('CertificationAuthority', models.CharField(blank=True, max_length=70, null=True)),
                ('FromYear', models.CharField(blank=True, max_length=70, null=True)),
                ('ToYear', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=5)),
                ('LanguageName', models.CharField(blank=True, max_length=70, null=True)),
                ('LanguageLevel', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='Description',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='FromYear',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='Title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='ToYear',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='WorkExperienceName',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
