# Generated by Django 3.0.7 on 2020-06-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200619_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
