# Generated by Django 3.0.7 on 2020-06-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200620_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='keywords',
            new_name='ozet',
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='cv',
            name='telefon',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
