# Generated by Django 3.0.7 on 2020-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200620_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='cv',
            name='telefon',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
