# Generated by Django 3.0.7 on 2020-06-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20200620_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cv',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
