# Generated by Django 3.0.7 on 2020-06-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_auto_20200627_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='DateOfBirth',
            field=models.DateField(blank=True, default=False),
        ),
    ]
