# Generated by Django 3.0.7 on 2020-06-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_auto_20200627_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='DateOfBirth',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
