# Generated by Django 3.0.7 on 2020-06-27 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_auto_20200627_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='DateOfBirth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
