# Generated by Django 3.0.7 on 2020-06-27 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_auto_20200627_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='DateOfBirth',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
