# Generated by Django 3.0.7 on 2020-06-27 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_remove_cv_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='DateOfBirth',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
