# Generated by Django 3.0.7 on 2020-06-27 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_cv_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='DateOfBirth',
            field=models.DateField(blank=True, default=datetime.date.today, editable=False),
        ),
    ]
