# Generated by Django 3.0.7 on 2020-06-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_auto_20200627_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='DateOfBirth',
        ),
    ]
